### ISSUE TITLE
Dear author, could you please see whether there is something wrong in the run files?

### ISSUE THREAD

**Issue by Jingxinxxxxxx** [tsinghua-fib-lab/Activity-Trajectory-Generation#2]
Hi yuanyuan:
  When I run the code, I find something wrong. However, I don't know what the problem is. Could you please give me some advise? Thanks a lot. There is something wrong 
in the app.py:
1、line 125”Trainer = Trainer_GAIL(args, device, TIME)“ ：no model named Trainer_GAIL
in the Trainer.py:
2、lin17:no reference "from models.spatial import GaussianMixtureSpatialModel, IndependentCNF"
3、line19：no reference”from models.temporal.basic import NeuralPointProcess“
4、line24:”from Evaluation import *":  Unresolved reference 'Evaluation' . I don't find which file is named Evaluation.
5、line28：”from viz_dataset import load_data, MAPS":  Unresolved reference 'viz_dataset' . I don't find which file is named viz_dataset.

**Comment by YuanYuan98** [comment]
I have updated the code, please refer to the new version~

**Comment by YuanYuan98** [comment]
Closed
