### ISSUE TITLE
about baselines

### ISSUE THREAD

**Issue by Gooood3** [tsinghua-fib-lab/Activity-Trajectory-Generation#3]
Dear yuanyuan, I am studying this paper of yours recently. In the baselines, I see that you run the SeqGAN to generate the active sequence. I would very sincerely like to know, when you generate data with SeqGAN, do you use the code that generates the experimental part of the synthetic data? I was generating active sequences with SeqGAN and the data generated was very homogeneous, and I have not been able to find a solution, so I am very interested to know how your experiments are carried out.
Thanks for your attention!

**Comment by YuanYuan98** [comment]
Sorry, I cannot get what this sentence means ( `do you use the code that generates the experimental part of the synthetic data`).  Could you please give a more detailed description?
