### ISSUE TITLE
About the disappeared args.t_max in app.py file

### ISSUE THREAD

**Issue by SUSTC-ChuangYANG** [tsinghua-fib-lab/Activity-Trajectory-Generation#4]
Dear Yuanyuan, 

I noticed that there is a important parameter called t_max in your code.
You invoke it by args.t_max,
But I can't find it in the config file `"app.py"`, 
I am not sure what might be causing this discrepancy, 
Could you please help me understand the issue? I would greatly appreciate any assistance you can provide. 
Thank you so much.

**Comment by YuanYuan98** [comment]
I have uploaded the file  `app.py`, please refer to it for detailed parameter configuration.
