### ISSUE TITLE
数据导入

### ISSUE THREAD

**Issue by DataScience-SX** [tsinghua-fib-lab/Activity-Trajectory-Generation#6]
data里面我看都是空的，而代码中有这样的数据导入：FileNotFoundError: [Errno 2] No such file or directory: '../data/Mobile/data.json'、请问能否提供可运行代码的样例数据，以供科学研究使用？谢谢您。

**Comment by YuanYuan98** [comment]
I have uploaded the Foursquare dataset. Please check [Foursquare data](https://github.com/tsinghua-fib-lab/Activity-Trajectory-Generation/tree/main/data/Foursquare).

**Comment by WaRr1or-USTB** [comment]
作者您好！请问数据集的时间戳是怎样的呢？
